version: '3.8'

services:
  app:
    build: .
    ports:
      - "9005:9005"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - .:/app
    networks:
      - app-network

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    
    networks:
      - app-network

networks:
  app-network:
    driver: bridge